### ISSUE TITLE
Lifetimes within procedural macros

### ISSUE THREAD

**Issue by zakcutner** [dustypomerleau/rust-syntax#11]
Hello and happy holidays ☃️  Thank you for creating this grammar, and it's great to see it used within VSCode. I've come across what I think may be a bug within the syntax highlighting rules for procedural macros attributes that include lifetime. As an example, take the following code snippet...

```rust
#[derive(Foo)]
#[foo('a)]
struct Bar<'a> { ... }
```

Whilst in GitHub none of the `foo('a)` is highlighted, this grammar highlights everything after the `'` as I presume it is mistaking this as the start of a quotation rather than as a lifetime. Since the 'quotation' is never ended, it then highlights `a)]` as well as the entirety of the next line too. In fact, it seems it will keep highlighting the rest of the file until another lifetime (i.e. a closing `'`) is found! The problem can also be extended to slightly more complex examples such as `#[foo('a, A)]` and `#[foo('a, 'b)]` (the second of which it will just highlight `a, `).

I would have tried to create a test case for this but I'm not quite sure what the intended behaviour is here. Both GitHub and the Rust playground seem to not highlight any kind of attribute or derive macros at all as far as I can tell, whereas this grammar will highlight the `Copy` within a `#[derive(Copy)]` for instance.

In case it helps, and just to motivate why there might be lifetimes like this within attribute macros, I thought I'd explain the context in which I ran into this. Let's say I create a trait `Foo` that looks something like this...

```rust
trait Foo<'a> { ... }
```

I may then want to create a derive macro in order to implement the trait. However, the macro wouldn't know which lifetime to use for `'a` when implementing for a struct which itself multiple lifetime. Therefore, as shown above, a derive macro helper attribute would probably be added for the user to specify this lifetime.

I hope this is useful, I'd be really happy to spend some more time investigating if that would help at all!

**Comment by dustypomerleau** [comment]
Thanks for reporting this. Fix on the way...

**Comment by zakcutner** [comment]
Perfect, thanks for this 😄
