### ISSUE TITLE
Distinguish Display, Debug and Debug's pretty-print interpolation symbols from operators

### ISSUE THREAD

**Issue by JKAnderson409** [dustypomerleau/rust-syntax#2]
```rust
// This example will show where I am noticing an issue.

let looks_good = format!("{} > {} | : | :? | :#?", 2, 1);
let looks_off = format!("{:?} > {:#?}", 2, 1);
```

The highlighting does not reflect that "{}", "{:?}" and "{:#?}" are all interpolation symbols. In the Ayu themes ":" and "?" look like operators while "{", "}" and "#" look like part of the string. When not inside of curly braces they all look like normal characters in a string, which is correct. I have also loaded up Yarra Valley and the issue is clearer because Yarra Valley seems to be giving coloration specifically for interpolation symbols.

I don't know TextMate well but I think the "keyword.operator.key-value.rust" and "keyword.operator.question.rust" scopes are taking precedence over the "meta.interpolation.rust" scope, leaving "#" out because that is not an operator. It seems to be correct in labeling these as Rust interpolation symbols it's just the operator scope taking precedence that causes the issue.

**Comment by dustypomerleau** [comment]
There are a couple of aspects to this. It's partly a discussion about how theme designers (or end users) can leverage meta scopes in textmate grammars, and partly a discussion of whether allowing other scopes inside `meta.interpolation` is a feature or a bug.

Regarding the first point, you can make the keywords inside interpolations any color you like (without affecting other keywords), by using the provided meta scope in your theme. So, as a simple example, you can theme

```json
"source.rust keyword"
```

differently from

```json
"source.rust meta.interpolation keyword"
```

Keep in mind that the grammar only supplies the scopes. It's up to the theme to specify the formatting for each stack of scopes.

Regarding the reason for allowing other scopes inside the interpolation brackets, my goal was twofold:

1. accomodate the full range of [named parameter](https://doc.rust-lang.org/std/fmt/#named-parameters) options that could be passed to `format!`
1. allow correct formatting of interpolated expressions for crates like [interpolate](https://docs.rs/interpolate/0.2.3/interpolate/)

However, I think your point is valid, in that operators and punctuation passed to `Display`, `Debug`, and `format!`, aren't necessarily viewed the same as in other contexts. In addition, I have reviewed the way the operators and punctuation look for all the different `format!` options, and it isn't working that well. As a result:

1. I'm pushing a patch update that will only contain 2 scopes inside string interpolations: `punctuation.definition.interpolation.rust` for the curly brackets, and `meta.interpolation.rust` for the contents. The meta scope will look the same for `Debug`, `Display`, `format!`, and the `interpolate` crate.
1. It's up to you how you want that to look. In Yarra Valley, interpolated expressions in other languages have a different color from the rest of the string, so I'll be keeping that convention. However, if you prefer, you can override that in any theme, and assign the highlight color for `meta.interpolation.rust` to the same value as `punctuation.definition.interpolation.rust`, `string.quoted.double.rust`, or any other value.
