### ISSUE TITLE
string.quoted.double.rust used twice

### ISSUE THREAD

**Issue by Proful** [dustypomerleau/rust-syntax#28]
`string.quoted.double.rust` used twice. Duplicate name.

**Comment by RedCMD** [comment]
they are for different rules?
![image](https://github.com/dustypomerleau/rust-syntax/assets/33529441/a294855c-1835-462c-aba8-2550daa60f4d)

**Comment by Wilfred** [comment]
Agreed, I don't think there's anything wrong with the current code. Let me know if I'm missing something :)
