### ISSUE TITLE
Incorrect scope for addition assignment operator '+='

### ISSUE THREAD

**Issue by TanakaDev** [dustypomerleau/rust-syntax#3]
Unlike '-=', '/=' and other similar operators, '+=' does not seem to have the correct scope.  Only the '=' part in the '+=' operator seems to work, meanwhile the '+' part just has the default 'source.rust' scope.  It seems to be an oversight with the TextMate JSON grammar file, as when I checked to see if it was being matched along with the other assignment operators, I could not find it.

**Comment by dustypomerleau** [comment]
Thanks for catching this. Fixed here and in Rust Analyzer.
