### ISSUE TITLE
Is this still maintained ?

### ISSUE THREAD

**Issue by GilShoshan94** [dustypomerleau/rust-syntax#39]
Hi @dustypomerleau ,

First of all, THANK YOU ! 
Thanks to you, to this repo and your theme Tol, I have an amazing experience developping Rust code in VsCode. (Same goes for the other Rust dev on VsCode I am sure.)

Now, the question, is this repo still maintained? According to the README.md:

> This extension provides a TextMate grammar for Rust. In most cases, you won't need to install the extension, as this repository is upstreamed by VS Code (issues and PRs should be submitted here).

And as I can see in the vscode repo, @alexr00 redericted people here for the issues and PRs.

Looking at the Issues, there are 9 open without any discussion/feedback. For more than a year, almost 2.
Those issues are relevant though...

Looking at the Pull request there are 6 open without any discussion/feedback. (1 for a year and the 5 others are more recents I admit).

I would love to see those PR merged and issues resolved.

@dustypomerleau, can you please comment if you are still willing to maintain this repo that the Rust community on VsCode use ? Or do you want to find another maintainer ?

**Comment by dustypomerleau** [comment]
Hi there, @GilShoshan94. You're right, of course. At the moment I don't have the personal or professional bandwidth to give this repo the attention it deserves.

The Rust community has rallied around Rust Analyzer's semantic highlighting, so I think the majority of Rustaceans (including myself) are not actually seeing these scopes, except as a rare fallback when not inside a Cargo workspace. I think the expectation for the future is that highlighting will be nuanced (distinguishing traits, structs, enums, and associated types, for example). This is very difficult with textmate scopes, but Rust Analyzer is handling it well. My overall impression has been that people use this grammar when they are first introduced to Rust, but quickly graduate to semantic highlighting when they discover Rust Analyzer. 

Of course, there may be users who prefer to disable semantic highlighting for some reason. I am willing to transfer the repo, if you are keen to maintain it—or to invite you as a collaborator.

**Comment by GilShoshan94** [comment]
I am using Rust Analyzer and semantic highlighting too.

I looked into it more as I was not really aware of the difference between [Syntax Highlight](https://code.visualstudio.com/api/language-extensions/syntax-highlight-guide) (TextMate) and [Semantic Highlight](https://code.visualstudio.com/api/language-extensions/semantic-highlight-guide).

You actually expained it well in your README.md. 
I got confused especially because the dev of `vscode` (@alexr00) redericted people here for the issues and PRs.

I looked at the open PRs, I don't have experience with TextMate but I uderstand that it's a matters of regex and associate it with the correct tags, all the PR seems good from reading the changes in the regexes. Just the last one (#38) is not clear to me and the one before (#37) while super cool I think I don't know if this has side effects...

But you are right, semantic highlighting powered by Rust Analyzer is more capable and is well founded, and as you said, the Rust community has rallied around Rust Analyzer's semantic highlighting.

---

I think the reasonable thing to do would be to merge the last 6 PR (if there are good of course) and then to archive this repo, so you won't accept any more issue nor PRs. 
And to let the dev of `vscode` redirect people to `rust-analyzer` for semantic highlighting issues.

So there would still be a good base TextMate grammar if someone needs, but it would be clear that no more development will be done.


> I am willing to transfer the repo, if you are keen to maintain it—or to invite you as a collaborator.

I can collaborate if you need help with the last 6 PRs, just let me know please how to verify/check those PR to not harm your work.

**Comment by alexr00** [comment]
Just a quick note: I direct people here for issues Rust syntax highlighting that occur when there is no other Rust extension installed. I'm happy to also recommend that folks install Rust Analyzer as well!

**Comment by icedrocket** [comment]
Hello @dustypomerleau,

Would you please consider merging #36 and #38, which are close to bug fixes? While it's true that rust-analyzer provides more accurate results, rust-syntax is still being used.

**Comment by icedrocket** [comment]
Hello @dustypomerleau,

Would you please consider merging #36 and #38, as they are closely related to bug fixes? While it's true that rust-analyzer provides more accurate results, rust-syntax is still being used.

**Comment by Wilfred** [comment]
This repository still handles syntax highlighting for basic cases: semantic highlighting is only an additional layer on top.

PRs like #36 definitely fix real issues for Rust users.

@dustypomerleau I've worked on other VS Code extensions (e.g. [vscode-hack](https://github.com/slackhq/vscode-hack/commits?author=Wilfred)), and I'd be interested in helping with this repository. How would you feel about adding me as a collaborator?

**Comment by dustypomerleau** [comment]
Thank you for stepping up, @Wilfred—you have full rights.
