### ISSUE TITLE
How to use this extension?

### ISSUE THREAD

**Issue by dbeckwith** [dustypomerleau/rust-syntax#4]
I installed this extension because I thought the default Rust syntax highlighting was lacking in VS Code, but I can't figure out how to get VS Code to use it. I also have the official rust-analyzer extension installed, and I saw #1, but I'm confused as to how to change the grammar association for Rust. I tried disabling the VS Code builtin Rust syntax extension, but now Rust files have no highlighting at all. Any ideas?

**Comment by dustypomerleau** [comment]
Hi, @dbeckwith. If you have enabled Rust Analyzer, then you don't need this extension. My grammar is merged into Rust Analyzer, and RA's grammar will overrides others when it starts. However, you won't see highlighting based on Textmate scopes unless you have semantic highlighting disabled in VS Code.

**Comment by dbeckwith** [comment]
Hmm okay, could it just be an issue with my theme then? It seems like most things are colored yellow in my theme and there isn't enough variation. I'm using the Cobalt2 theme.
![image](https://user-images.githubusercontent.com/1279939/98428694-a5803180-2070-11eb-99ca-93f65b592774.png)

**Comment by dustypomerleau** [comment]
The Textmate grammar only provides the scopes. If you don't like the color applied to one of the tokens, you can override it in `settings.json`. It just happens that your theme is using the same color for `storage`, `entity.name...`, and `function`. You can see the scope names for customization using `Developer: Inspect Editor Tokens And Scopes`.

**Comment by dbeckwith** [comment]
Okay thanks, I'll try customizing it. Do you have an example theme that assigns different colors to the different scopes that I could try to verify that it's working? Like the one in the screenshot in the README?

**Comment by dustypomerleau** [comment]
My [Yarra Valley](https://marketplace.visualstudio.com/items?itemName=dustypomerleau.yarra-valley) theme should work. There is a screenshot of Rust code in the README.

**Comment by dbeckwith** [comment]
Thanks!

With your theme I think I was able to find a parsing bug haha. The macro metavariable type `path` looks like it's being parsed as `pat`:
![image](https://user-images.githubusercontent.com/1279939/98430837-9607e500-207e-11eb-897f-0e25120e060a.png)

**Comment by dustypomerleau** [comment]
Thanks for catching that—I have pushed a fix.
